### ISSUE TITLE
Transactions Tab

### ISSUE THREAD

**Issue by coderofstuff** [coderofstuff/kasvault#1]
Current Transactions Tab will fetch the latest 10 transactions only

- [x] Implement pagination
- [x] Make it look better

**Comment by eladitzhakian** [comment]
> Current Transactions Tab will fetch the latest 10 transactions only

Is this stlil correct? In demo mode it looks like pagination is working

**Comment by coderofstuff** [comment]
> > Current Transactions Tab will fetch the latest 10 transactions only
> 
> Is this stlil correct? In demo mode it looks like pagination is working

Already fixed. Closing this
